alias l='ls --color=auto -ACFrt'
alias ll='ls --color=auto -AFlrt'
alias browse_to_rstudio="distrobox-host-exec xdg-open http://localhost:8787"

export EDITOR=/usr/bin/vim
export VISUAL=/usr/bin/vim
export PROJECTS=$HOME/Projects
export LOGFILES=$HOME/Logfiles

# Ollama
export OLLAMA_TARBALL="ollama-linux-amd64.tar.zst"
export OLLAMA_VERSION="v0.14.3"
export OLLAMA_URL="https://github.com/ollama/ollama/releases/download/${OLLAMA_VERSION}/${OLLAMA_TARBALL}"
export OLLAMA_API_BASE=http://127.0.0.1:11434

# Python venvs
export AIDER_VENV="$HOME/.python_venvs/aider"
